name: shopease
description: ShopEase flutter application
version: 0.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  http_mock_adapter: ^0.6.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: 26fedcee4b0e6f7a85f65f1fb48834a21f57e970

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/png/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - animations/
    - images/svg/
    - images/png/

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.4.3+1
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.1.0
  currency_text_input_formatter: ^2.1.7
  google_fonts: 6.1.0
  device_info_plus: ^9.0.2
  page_transition: ^2.0.9
  device_preview: ^1.2.0
  flutter_screenutil: ^5.6.1
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_local_notifications: ^17.0.1
  super_tooltip: ^2.0.7
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  flutter_vibrate: ^1.3.0
  store_redirect: ^2.0.2
  shimmer: ^3.0.0
  package_info_plus: ^4.2.0
  flutter_datetime_picker_plus: ^2.1.0
  flutter_switch: ^0.3.2

  #Firebase
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5

